on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: "Environment"
        options:
          - dev
          - test
          - prod

name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
          targetEnv: ${{ inputs.environment }}
    steps:

      # Checkout code
    - uses: actions/checkout@main

      
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: subscription
        region: northeurope
        template: ./Bicep-Templates/main.bicep
