on: 
  workflow_dispatch:
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
  
      if: github.ref == 'refs/heads/main'
      - name: Set Environment Variable
        run: echo "::set-env name=targetEnv::$(cat ./Bicep-Templates/main.bicep | grep 'webAppName' | cut -d "'" -f 2 | sed 's/-dev/-test/')"
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: subscription
        region: northeurope
        template: ./Bicep-Templates/main.bicep
        overrideParameters: targetEnv=${{ env.targetEnv }}


